name: Create a new app

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ bc-build ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0092"

  CreateApp:
    runs-on: [ bc-build ]
    needs: [ Initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: freddydk/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: type

      - name: Creating a new app
        uses: freddydk/AL-Go-Actions/CreateApp@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

  PostProcess:
    if: always()
    runs-on: [ bc-build ]
    needs: [ Initialization, CreateApp ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0092"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
