name: Create Online Dev. Environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: Name of the online environment
        required: true
      reUseExistingEnvironment:
        description: Reuse environment if it exists
        required: false
        default: 'N'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ bc-build ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0093"

  CreateEnvironment:
    runs-on: [ bc-build ]
    needs: [ Initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: freddydk/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: freddydk/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'adminCenterApiCredentials'

      - name: Check AdminCenterApiCredentials / Initiate Device Login (open to see code)
        run: |
          $adminCenterApiCredentials = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:adminCenterApiCredentials))
          if ($adminCenterApiCredentials) {
            Write-Host "AdminCenterApiCredentials provided!"
          }
          else {
            Write-Host "AdminCenterApiCredentials not provided, initiating Device Code flow"
            $ALGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
            $webClient = New-Object System.Net.WebClient
            $webClient.DownloadFile('https://raw.githubusercontent.com/freddydk/AL-Go-Actions/main/AL-Go-Helper.ps1', $ALGoHelperPath)
            . $ALGoHelperPath
            $BcContainerHelperPath = DownloadAndImportBcContainerHelper -baseFolder $ENV:GITHUB_WORKSPACE
            $authContext = New-BcAuthContext -includeDeviceLogin -deviceLoginTimeout ([TimeSpan]::FromSeconds(0))
            MaskValueInLog -value $authContext.deviceCode
            Add-Content -Path $env:GITHUB_ENV -Value "adminCenterApiCredentials={""deviceCode"":""$($authContext.deviceCode)""}"
            CleanupAfterBcContainerHelper -bcContainerHelperPath $bcContainerHelperPath
          }

      - name: Create Development Environment
        uses: freddydk/AL-Go-Actions/CreateDevelopmentEnvironment@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          environmentName: ${{ github.event.inputs.environmentName }} 
          reUseExistingEnvironment: ${{ github.event.inputs.reUseExistingEnvironment }} 
          directCommit: ${{ github.event.inputs.directCommit }} 
          adminCenterApiCredentials: ${{ env.adminCenterApiCredentials }} 

  PostProcess:
    if: always()
    runs-on: [ bc-build ]
    needs: [ Initialization,  CreateEnvironment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0093"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
