name: Update Baseline Version

on:
  workflow_dispatch:
  schedule:
    - cron: "55 03 * * *" # Run at 03:55 UTC on Tuesday

defaults:
  run:
    shell: powershell

env:
  repoName: ${{ github.event.repository.name }}

jobs:
  UpdateBaseline:
    if: github.repository_owner == 'microsoft'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update Baseline Version
        run: | 
          Build/Scripts/UpdateBaselineVersion.ps1 -TargetBranch $env:GITHUB_REF_NAME -Actor $env:GITHUB_ACTOR
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
